kernel:
  image: linuxkit/kernel:4.14.27
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:b212cfeb4bb6330e0a7547d8010fe2e8489b677a
  - linuxkit/runc:7c39a68490a12cde830e1922f171c451fb08e731
  - linuxkit/containerd:37e397ebfc6bd5d8e18695b121166ffd0cbfd9f0
services:
  - name: getty
    image: conf-linuxkit/lkt-hello-world:0d8e9e6ea60c3423f7d676c389cf52a1450e4b53-amd64
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
