kernel:
  image: linuxkit/kernel:4.14.34
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:v0.3
  - linuxkit/runc:v0.3
  - linuxkit/containerd:v0.3
services:
  - name: getty
    image: conf-linuxkit/lkt-hello-world:v0.1
    env:
     - INSECURE=true
trust:
  org:
    - linuxkit
